version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Map to host port for app access
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=myapp
      - URL=localhost:8080
    depends_on:
      - db
    networks:
      - internal_network

  db: 
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
